CoreBlogProject/Areas/Management/Controllers/SlugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreBlogProject.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace CoreBlogProject.Areas.Management.Controllers
{
    [Area("Management")]
    [Route("Management/[controller]/[action]")]
    public class SlugController : Controller
    {
        [HttpPost]
        public string ConvertToSlug(string title)
        {
            return UrlServices.URLFriendly(title);
        }
    }
}

CoreBlogProject/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CoreBlogProject.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CoreBlogProject/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CoreBlogProject.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CoreBlogProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@ViewData["Title"] - CoreBlogProject</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">


    <link href="~/css/open-iconic-bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/animate.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/css/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/css/aos.css" rel="stylesheet" />
    <link href="~/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap-datepicker.css" rel="stylesheet" />
    <link href="~/css/jquery.timepicker.css" rel="stylesheet" />
    <link href="~/css/flaticon.css" rel="stylesheet" />
    <link href="~/css/icomoon.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>

<body>

    <div id="colorlib-page">
        <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
        <aside id="colorlib-aside" role="complementary" class="js-fullheight">
            <nav id="colorlib-main-menu" role="navigation">
                <ul>
                    <li class="colorlib-active">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li><a asp-controller="About" asp-action="Index">About</a></li>
                    <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-link text-dark" asp-area="Management" asp-controller="Management" asp-action="Index">Management</a></li>
                    }

                    <li>
                        <partial name="_LoginPartial" />
                    </li>
                </ul>
            </nav>

            <div class="colorlib-footer">
                <p class="pfooter">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is
                    made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com"
                                                                                  target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </aside> <!-- END COLORLIB-ASIDE -->
        <div id="colorlib-main">
            <section class="ftco-section ftco-no-pt ftco-no-pb">
                <div class="container">
                    <div class="row d-flex">
                        <div class="col-xl-12 py-4 px-md-4">

                                @RenderBody()

        

                        </div>

                    </div>
                </div>
            </section>
        </div><!-- END COLORLIB-MAIN -->
    </div><!-- END COLORLIB-PAGE -->
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00" />
        </svg>
    </div>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/Slug.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
         slug.init("@Url.Action("ConvertToSlug", "Slug", new { area = "Management" })");
    </script>
    @RenderSection("Scripts", required: false)

</body>

</html>

CoreBlogProject/Views/Shared/_PostContentPartial.cshtml
@model Post

<div class="col-md-12">
    <div class="blog-entry ftco-animate d-md-flex">
        <img src="~/Images/@Model.PhotoPath" alt="Alternate Text" width="150" height="150" style="border-radius:50%;" />
        <div class="text text-2 pl-md-4">
            <h3 class="mb-2">
                <a href="single.html">
                    @Model.Title
                </a>
            </h3>
            <div class="meta-wrap">
                <p class="meta">
                    <span><i class="icon-calendar mr-2"></i>@Model.AddTime</span>
                    <span>
                        <a href="single.html">
                            <i class="icon-folder-o mr-2"></i>@Model.Category.CategoryName
                        </a>
                    </span>
                    @*<span><i class="icon-comment2 mr-2"></i></span>*@
                </p>
            </div>
            <p class="mb-4">
                @Model.Content
            </p>
            <p>
                <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.PostId" class="btn-custom">
                    Read More <span class="ion-ios-arrow-forward"></span>
                </a>
            </p>
        </div>
    </div>
</div>