CoreBlogProject/Areas/Management/Controllers/CategoriesController.cs
using CoreBlogProject.Areas.Management.ViewModels;
using CoreBlogProject.Helpers;
using CoreBlogProject.Models;
using CoreBlogProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CoreBlogProject.Areas.Management.Controllers
{
    [Area("Management")]
    [Route("Management/[controller]/[action]")]
    //[Authorize]
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoriesController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        // GET: CategoriesController
        public ActionResult Index()
        {
            return View(_categoryRepository.AllCategories);
        }


        // GET: CategoriesController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CategoriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryViewModel cvm)
        {
            if (ModelState.IsValid)
            {
                Category newCategory = new Category
                {
                    CategoryId = cvm.CategoryId,
                    CategoryName = cvm.CategoryName,
                    Slug = UrlServices.URLFriendly(cvm.Slug)
                };
                _categoryRepository.CreateCategory(newCategory);
                if (await _categoryRepository.SaveChangesAsync())
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View();

        }

        // GET: CategoriesController/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new Category());
            }
            var category = _categoryRepository.GetCategoryId((int)id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: CategoriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (category.CategoryId > 0)
            {
                _categoryRepository.UpdateCategory(category);
            }
            _categoryRepository.CreateCategory(category);
            if (await _categoryRepository.SaveChangesAsync())
            {
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        // POST: CategoriesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            _categoryRepository.DeleteCategory(id);
            await _categoryRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

CoreBlogProject/Areas/Management/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreBlogProject.Areas.Management.ViewModels;
using CoreBlogProject.Helpers;
using CoreBlogProject.Interfaces;
using CoreBlogProject.Models;
using CoreBlogProject.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreBlogProject.Areas.Management.Controllers
{
    [Area("Management")]
    [Route("Management/[controller]/[action]")]
    //[Authorize]
    public class PostsController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IFileManager _file;
        private readonly ICategoryRepository _categoryRepository;

        public PostsController(IPostRepository postRepository, IFileManager file, ICategoryRepository categoryRepository)
        {
            _postRepository = postRepository;
            _file = file;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {
            return View(_postRepository.AllPosts);
        }

        public IActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePostModel cpm)
        {
            if (ModelState.IsValid)
            {
                Post newPost = new Post
                {
                    CategoryId = cpm.CategoryId,
                    Title = cpm.Title,
                    Content = cpm.Content,
                    PhotoPath = await _file.SaveImages(cpm.PhotoPath),
                    Slug = UrlServices.URLFriendly(cpm.Slug),
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
                _postRepository.CreatePost(newPost);
                if (await _postRepository.SaveChangesAsync())
                {
                    return RedirectToAction("Index");
                }

            }
            //Dropddown'da category name cagırmak için category ıd cagırılacak
           ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName");
            return View();
        }


        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new Post());
            }
            var post = _postRepository.GetPostId((int)id);
            if (post == null)
            {
                return NotFound();
            }
            ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName");
            return View(post);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Post post)
        {
            if (post.PostId > 0)
            {
                if (post.PhotoPath != null)
                {
                    _file.DeleteImage(post.PhotoPath);
                }
                
                _postRepository.UpdatePost(post);
            }

            _postRepository.CreatePost(post);

            if (await _postRepository.SaveChangesAsync())
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName");
            return View(post);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            _postRepository.DeletePost(id);
            await _postRepository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

CoreBlogProject/Areas/Management/Controllers/SlugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreBlogProject.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace CoreBlogProject.Areas.Management.Controllers
{
    [Area("Management")]
    [Route("Management/[controller]/[action]")]
    public class SlugController : Controller
    {
        [HttpPost]
        public string ConvertToSlug(string title)
        {
            return UrlServices.URLFriendly(title);
        }
    }
}

CoreBlogProject/Areas/Management/Views/Shared/_DeleteModalPartial.cshtml
<form id="deleteModalForm" action="" method="post">
    @Html.AntiForgeryToken()
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <input id="deleteModalItemId" type="hidden" name="Id" />
                <div class="modal-body">
                    Are you sure to delete the item &quot;<span id="deleteModalItemName"></span>&quot;?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Yes, Delete It</button>
                </div>
            </div>
        </div>
    </div>
</form>

CoreBlogProject/Areas/Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="~/css/adminlte.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-controller="Management" asp-action="Index">Management</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <i class="fab fa-meetup"></i>
                <span class="brand-text font-weight-light">Management</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link active">
                                <i class="fab fa-cuttlefish"></i>
                                <p>
                                    Category
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Categories" asp-action="Index">
                                        <i class="fas fa-clipboard-list"></i>
                                        <p>List</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Categories" asp-action="Create">
                                        <i class="fas fa-folder-plus"></i>
                                        <p>Create</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link active">
                                <i class="fab fa-usps"></i>
                                <p>
                                    Posts
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Posts" asp-action="Index">
                                        <i class="fas fa-clipboard-list"></i>
                                        <p>List</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Posts" asp-action="Create">
                                        <i class="fas fa-folder-plus"></i>
                                        <p>Create</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Dashboard</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a asp-controller="Management" asp-action="Index">Home</a></li>
                                <li class="breadcrumb-item active">Management</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2020 <a href="https://burakturkozen.com">Burak TÜRKÖZEN</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <a href="https://github.com/BTurkozen"><b>BTurkozen</b></a>
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>

    <script src="~/plugins/jquery/jquery.js"></script>
    <script src="~/plugins/popper/popper.js"></script>


    <script src="~/datatables/js/jquery.dataTables.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="~/plugins/bs-custom-file-input/bs-custom-file-input.js"></script>
    <script src="~/plugins/summernote/summernote-bs4.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/js/pages/dashboard.js"></script>
    <script src="~/js/demo.js"></script>
    <script src="~/js/Slug.js"></script>
    <script src="~/js/management.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
         slug.init("@Url.Action("ConvertToSlug", "Slug", new { area = "Management" })");
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>